// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: translate/testdata/proto/order.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_translate_testdata_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_translate_testdata_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_translate_testdata_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_translate_testdata_proto_order_proto protoreflect.FileDescriptor

const file_translate_testdata_proto_order_proto_rawDesc = "" +
	"\n" +
	"$translate/testdata/proto/order.proto\x12\btestdata\x1a'third_party/buf/validate/validate.proto\"E\n" +
	"\x05Order\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x04R\x02id\x12#\n" +
	"\bquantity\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bquantityBMZKgithub.com/jzero-io/protovalidate-translator/examples/translate/testdata/pbb\x06proto3"

var (
	file_translate_testdata_proto_order_proto_rawDescOnce sync.Once
	file_translate_testdata_proto_order_proto_rawDescData []byte
)

func file_translate_testdata_proto_order_proto_rawDescGZIP() []byte {
	file_translate_testdata_proto_order_proto_rawDescOnce.Do(func() {
		file_translate_testdata_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translate_testdata_proto_order_proto_rawDesc), len(file_translate_testdata_proto_order_proto_rawDesc)))
	})
	return file_translate_testdata_proto_order_proto_rawDescData
}

var file_translate_testdata_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_translate_testdata_proto_order_proto_goTypes = []any{
	(*Order)(nil), // 0: testdata.Order
}
var file_translate_testdata_proto_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_translate_testdata_proto_order_proto_init() }
func file_translate_testdata_proto_order_proto_init() {
	if File_translate_testdata_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translate_testdata_proto_order_proto_rawDesc), len(file_translate_testdata_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_translate_testdata_proto_order_proto_goTypes,
		DependencyIndexes: file_translate_testdata_proto_order_proto_depIdxs,
		MessageInfos:      file_translate_testdata_proto_order_proto_msgTypes,
	}.Build()
	File_translate_testdata_proto_order_proto = out.File
	file_translate_testdata_proto_order_proto_goTypes = nil
	file_translate_testdata_proto_order_proto_depIdxs = nil
}
